.\" $Header: /data/zender/nco_20150216/nco/man/ncpdq.1,v 1.25 2013-06-30 05:15:16 zender Exp $ -*-nroff-*-
.\" Purpose: ROFF man page for ncpdq 
.\" Usage:
.\" nroff -man ~/nco/man/ncpdq.1 | less
.TH NCPDQ 1
.SH NAME
ncpdq \- netCDF Permute Dimensions Quickly, Pack Data Quietly...
.SH SYNTAX
ncpdq [\-3] [\-4] [\-6] [\-A] [\-a 
.IR dim [,...]]
[\-\-bfr
.IR sz ] [\-C] [\-c] [\-D 
.IR dbg_lvl ]
[\-d 
.IR dim ,[
.IR min ][,[
.IR max ]]]
[\-F] [\-G
.IR gpe_dsc ]
[\-g  
.IR grp [,...]]
[\-h] [\-\-hdr_pad
.IR sz ]
[\-L 
.IR dfl_lvl ] 
[\-l 
.IR path ]
[\-M 
.IR pck_map ]
[\-\-no_tmp_fl] [\-O] [\-o 
.IR output-file ]
[\-P 
.IR pck_plc ]
[\-p 
.IR path ]
[\-R] [\-r] [\-\-ram_all] [\-t 
.IR thr_nbr ] 
[\--unn] [\-v 
.IR var [,...]]
[\-X 
.IR box ] 
[\-x] 
.IR input-file
[
.IR output-file
]
.SH DESCRIPTION
.PP
.B ncpdq
packs or re-shapes variables in 
.I input-file
and stores them in 
.I output-file.
Which variables to pack/unpack are determined by the packing policy 
encoded in the 
.IR pck_plc 
argument to the 
.BR \-P
switch.
Valid 
.IR pck_plc 
options are
.IR all_new, 
.IR all_xst, 
.IR xst_new, 
and
.IR upk.
The numeric type of variable to pack or re-pack a variable to is
determined by the packing map encoded in the 
.IR pck_map
argument to the 
.BR \-M
switch.
Valid 
.IR pck_map
options are
.IR flt_byt,
.IR flt_sht,
.IR hgh_byt,
.IR hgh_sht,
and
.IR nxt_lsr.

.B ncpdq 
re-shapes variables in 
.I input-file
by re-ordering and/or reversing dimensions specified in the dimension list.
The dimension list is a comma separated list of dimension names,
optionally prefixed by negative signs, that follow the 
.BR \-a
switch. 
To re-order variables by a subset of their dimensions, specify
these dimensions in a comma-separated list following
.BR \-a ,
e.g.,
.BR "\-a lon,lat".
To reverse a dimension, prefix its name with a negative sign in the
dimension list, e.g., 
.BR "\-a \-lat". 
Re\-ordering and reversal may be performed simultaneously, e.g.,
.BR "\-a lon,\-lat,time,\-lev". 

Users may specify any permutation of dimensions, including
permutations which change the record dimension identity.
The record dimension is re-ordered like any other dimension.
The record dimension is always the most slowly varying dimension in a
record variable.
The specified re-ordering will fail if it requires creating more than
one record dimension amongst all the output variables.

.\" NB: Append man_end.txt here
.\" $Header: /data/zender/nco_20150216/nco/man/ncpdq.1,v 1.25 2013-06-30 05:15:16 zender Exp $ -*-nroff-*-
.\" Purpose: Trailer file for common ending to NCO man pages
.\" Usage: 
.\" Append this file to end of NCO man pages immediately after marker
.\" that says "Append man_end.txt here"
.SH AUTHOR
.B NCO
manual pages written by Charlie Zender and originally formatted by Brian Mays.

.SH "REPORTING BUGS"
Report bugs to <http://sf.net/bugs/?group_id=3331>.

.SH COPYRIGHT
Copyright \(co 1995-2010 Charlie Zender
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

.SH "SEE ALSO"
The full documentation for
.B NCO
is maintained as a Texinfo manual called the 
.B NCO User's Guide.
Because 
.B NCO
is mathematical in nature, the documentation includes TeX-intensive
portions not viewable on character-based displays. 
Hence the only complete and authoritative versions of the 
.B NCO User's Guide 
are the PDF (recommended), DVI, and Postscript versions at
<http://nco.sf.net/nco.pdf>, <http://nco.sf.net/nco.dvi>,
and <http://nco.sf.net/nco.ps>, respectively.
HTML and XML versions
are available at <http://nco.sf.net/nco.html> and
<http://nco.sf.net/nco.xml>, respectively.

If the
.B info
and
.B NCO
programs are properly installed at your site, the command
.IP
.B info nco
.PP
should give you access to the complete manual, except for the
TeX-intensive portions.

.SH HOMEPAGE
The 
.B NCO
homepage at <http://nco.sf.net> contains more information.
