.TH NCPDQ 1
.SH NAME
ncpdq \- netCDF Permute Dimensions Quickly
.SH SYNTAX
ncpdq [-A] [-a 
.IR dim [,...]]
[-C] [-c] [-D 
.IR dbg ]
[-d 
.IR dim ,[
.IR "min" ][,[
.IR max ]]]
[-F]
[-h] [-l 
.IR path ]
[-O] [-o 
.IR output-file ]
[-p 
.IR path ]
[-R] [-r] 
[-t 
.IR thr_nbr ] [-v 
.IR var [,...]]
[-x] 
.I input-file [
.I output-file ]
.SH DESCRIPTION
.PP
.B ncpdq

.B ncpdq
re-shapes variables in 
.I input-file
by re-ordering
their dimensions as specified in the dimension re-order list.
The record dimension is re-ordered like any other dimension.
To re-order variable by a subset of their dimensions, specify
these dimensions in a comma-separated list following
.BR -a ,
e.g.,
.BR "-a lon,lat".

Users may specify any permutation of dimensions, including
permutations which change the record dimension identity.
The record dimension is always the most slowly varying dimension in a
record variable.
The specified re-ordering will fail if it requires creating more than
one record dimension amongst all the output variables.
