#!/bin/sh
set -e

if [ "$1" = configure ]; then
    install-info --quiet \
      --section "netCDF" "netCDF" \
      --description="netCDF Operator suite." \
      /usr/share/info/nco.info
fi

#DEBHELPER#
