#!/bin/sh -e

# Automatically added by dh_installdocs
if [ "$1" = remove ] || [ "$1" = upgrade ] && \
   which install-docs >/dev/null 2>&1; then
	install-docs -r nco
fi
# End automatically added section
# Automatically added by dh_installinfo
install-info --quiet --remove /usr/share/info/nco.info
# End automatically added section
