rmdir antlr2\lib\cpp\build /s /q
rmdir curl\builds /s /q
rmdir gsl\build /s /q
rmdir hdf5\build /s /q
rmdir libexpat\expat\build /s /q
rmdir netcdf-c\build /s /q
rmdir szip\build /s /q
rmdir UDUNITS-2\build /s /q
rmdir zlib\build /s /q
rmdir CMakeFiles /s /q
rmdir x64 /s /q
rmdir Debug /s /q
rmdir nco.dir /s /q
rmdir ncks.dir /s /q
rmdir ncbo.dir /s /q
rmdir ncecat.dir /s /q
rmdir ncflint.dir /s /q
rmdir ncpdq.dir /s /q
rmdir ncra.dir /s /q
rmdir ncrename.dir /s /q
rmdir ncatted.dir /s /q
rmdir ncwa.dir /s /q
rmdir ncap2.dir /s /q
