rmdir CMakeFiles /s /q
rmdir x64 /s /q
rmdir Debug /s /q
rmdir ncks.dir /s /q
rmdir nco.dir /s /q
rmdir ncbo.dir /s /q
rmdir ncecat.dir /s /q
rmdir ncflint.dir /s /q
rmdir ncpdq.dir /s /q
rmdir ncra.dir /s /q
rmdir ncrename.dir /s /q
rmdir ncatted.dir /s /q
rmdir ncwa.dir /s /q
rmdir ncap2.dir /s /q
